# Generated by Django 3.2.5 on 2021-08-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='rec_new_msg',
            field=models.CharField(choices=[('all', 'Receive all new messages'), ('follow', 'Receive new messages only from users I follow'), ('block', 'Block all new messages')], default='all', max_length=8),
        ),
    ]
